-- The base schema as it existed before Flyway was introduced (originally created by
-- Hibernate's ddl-auto=update in early local development - see application.properties'
-- comment on spring.flyway.baseline-on-migrate). V1 onward only ever capture INCREMENTAL
-- changes on top of this; none of them create these core tables.
--
-- On an environment that already has this schema (local dev, any already-deployed
-- instance), baseline-on-migrate/baseline-version=0 mean this file is silently skipped -
-- Flyway treats anything at or below the baseline version as already covered. On a
-- genuinely empty database (a fresh Postgres instance, e.g. on Render), there is no
-- baseline yet, so this runs first, then V1 onward apply normally on top of it.
--
-- Deliberately excludes anything a later migration creates from scratch (invite_codes -
-- V2, email_verification_codes - V7) and adds later-added columns as NULLable/absent so
-- the later ALTER-based migrations (V1, V3, V5, V6, V7, V8) can apply their changes
-- exactly as written, unmodified.
--
-- Rollback: see rollback/R0__drop_base_schema.sql

create table authors (id integer generated by default as identity, created_at timestamp(6) not null, full_name varchar(200) not null, bio TEXT, primary key (id));
create table publishers (id integer generated by default as identity, created_at timestamp(6) not null, country varchar(100), name varchar(200) not null, primary key (id));
create table categories (id integer generated by default as identity, parent_id integer, created_at timestamp(6) not null, name varchar(100) not null, description TEXT, primary key (id));
create table roles (id integer generated by default as identity, name varchar(50) not null unique, primary key (id));

create table institutions (institution_id integer generated by default as identity, is_active boolean not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, tier varchar(20) not null, phone varchar(30), short_name varchar(50) unique, city varchar(100), country varchar(100), email varchar(150), name varchar(200) not null, primary key (institution_id));

create table users (id integer generated by default as identity, institution_id integer, is_active boolean not null, index_number varchar(7), student_id varchar(8), phone_number varchar(30), first_name varchar(100) not null, last_name varchar(100) not null, email varchar(150) not null unique, programme varchar(150), profile_image_url varchar(500), push_token varchar(500), password varchar(255) not null, primary key (id));

create table user_roles (role_id integer not null, user_id integer not null, primary key (role_id, user_id));

create table books (available_copies integer not null, borrow_count integer not null, category_id integer, id integer generated by default as identity, institution_id integer, is_active boolean not null, is_digital_only boolean not null, publication_year smallint, publisher_id integer, total_copies integer not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, isbn varchar(20) unique, isbn13 varchar(20) unique, dewey_decimal varchar(50), edition varchar(50), language varchar(50), location_code varchar(50), cover_image_url varchar(500), digital_url varchar(500), subtitle varchar(500), title varchar(500) not null, content TEXT, description TEXT, primary key (id));

create table book_authors (author_id integer not null, book_id integer not null, primary key (author_id, book_id));
create table book_copies (acquired_at date, book_id integer not null, id integer generated by default as identity, is_available boolean not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, condition varchar(20), barcode varchar(100) unique, notes TEXT, primary key (id));
create table book_views (book_id integer not null, id integer generated by default as identity, user_id integer not null, viewed_at timestamp(6) not null, primary key (id));
create table bookmarks (book_id integer not null, id integer generated by default as identity, user_id integer not null, created_at timestamp(6) not null, primary key (id), constraint uk_bookmarks_user_book unique (user_id, book_id));

create table courses (id integer generated by default as identity, institution_id integer not null, created_at timestamp(6) not null, updated_at timestamp(6), code varchar(20), status varchar(20) not null, name varchar(100) not null, description TEXT, primary key (id));
create table course_books (book_id integer not null, course_id integer not null, primary key (book_id, course_id));

create table borrow_records (book_id integer not null, copy_id integer, due_date date not null, id integer generated by default as identity, renewal_count smallint not null, reservation_id integer, user_id integer, borrowed_at timestamp(6) not null, created_at timestamp(6) not null, returned_at timestamp(6), updated_at timestamp(6) not null, status varchar(20) not null, notes TEXT, primary key (id));
create table reservations (book_id integer not null, id integer generated by default as identity, queue_position integer, user_id integer not null, cancelled_at timestamp(6), collected_at timestamp(6), created_at timestamp(6) not null, expires_at timestamp(6), ready_at timestamp(6), reserved_at timestamp(6) not null, updated_at timestamp(6) not null, status varchar(20) not null, cancel_reason TEXT, notes TEXT, primary key (id));
create table pickup_slots (collected_by integer, id integer generated by default as identity, loan_id integer, reservation_id integer not null, user_id integer not null, collected_at timestamp(6), created_at timestamp(6) not null, scheduled_at timestamp(6) not null, slot_end timestamp(6), slot_start timestamp(6), updated_at timestamp(6), status varchar(20) not null, qr_code varchar(100) not null unique, primary key (id));

create table fines (amount numeric(10,2) not null, borrow_id integer, id integer generated by default as identity, user_id integer not null, created_at timestamp(6) not null, due_date timestamp(6), updated_at timestamp(6), status varchar(20) not null, reason TEXT, primary key (id));
create table fine_payments (amount numeric(10,2) not null, amount_paid numeric(10,2) not null, fine_id integer not null, id integer generated by default as identity, user_id integer not null, created_at timestamp(6) not null, paid_at timestamp(6) not null, payment_method varchar(50), transaction_ref varchar(100) unique, primary key (id));

create table notifications (id integer generated by default as identity, is_read boolean not null, reference_id integer, user_id integer not null, created_at timestamp(6) not null, read_at timestamp(6), sent_at timestamp(6), channel varchar(20), reference_type varchar(50), title varchar(200) not null, message TEXT not null, type varchar(255) not null, primary key (id));

create table reading_lists (course_id integer not null, created_by integer, id integer generated by default as identity, is_published boolean not null, created_at timestamp(6) not null, published_at timestamp(6), updated_at timestamp(6), academic_year varchar(20), semester varchar(20), title varchar(300), description TEXT, primary key (id));
create table reading_list_items (book_id integer not null, id integer generated by default as identity, reading_list_id integer not null, created_at timestamp(6) not null, required_by timestamp(6), updated_at timestamp(6), notes TEXT, primary key (id));
create table student_reading_progress (id integer generated by default as identity, list_item_id integer not null, student_id integer not null, created_at timestamp(6) not null, updated_at timestamp(6), status varchar(20) not null, primary key (id), constraint uk_student_reading_progress_student_item unique (student_id, list_item_id));

create table audio_tracks (book_id integer not null, duration_seconds integer, id integer generated by default as identity, user_id integer not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, language_code varchar(10), audio_format varchar(20), status varchar(20) not null, voice_name varchar(100), title varchar(300) not null, audio_url varchar(1000), content TEXT, error_message TEXT, audio_data bytea, primary key (id));
create table audio_book_tracks (book_id integer, duration_seconds integer not null, file_size_bytes float(53), id integer generated by default as identity, is_available_offline boolean not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, course_code varchar(50), audio_url varchar(500) not null, cover_image_url varchar(500), title varchar(500) not null, author varchar(255), primary key (id));
create table user_audio_progress (current_position_seconds integer not null, id integer generated by default as identity, is_completed boolean not null, track_id integer not null, user_id integer not null, last_listened_at timestamp(6) not null, primary key (id), constraint uk_user_audio_progress_user_track unique (user_id, track_id));

create table exam_questions (book_id integer, id integer generated by default as identity, is_correct boolean, session_id integer, user_id integer not null, created_at timestamp(6) not null, difficulty varchar(20), question_type varchar(30), correct_answer TEXT not null, explanation TEXT, option_a TEXT, option_b TEXT, option_c TEXT, option_d TEXT, question TEXT not null, user_answer TEXT, primary key (id));
create table study_sessions (book_id integer, correct_answers integer, id integer generated by default as identity, is_completed boolean not null, total_questions integer, user_id integer not null, completed_at timestamp(6), created_at timestamp(6) not null, started_at timestamp(6) not null, session_type varchar(30), primary key (id));
create table study_summaries (book_id integer not null, id integer generated by default as identity, user_id integer not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, status varchar(20) not null, summary_type varchar(50), title varchar(300) not null, error_message TEXT, original_text TEXT, summary_text TEXT, primary key (id));

create table audit_logs (entity_id integer, id integer generated by default as identity, user_id integer, created_at timestamp(6) not null, entity_type varchar(50), ip_address varchar(50), action varchar(100) not null, details TEXT, primary key (id));
create table search_logs (id integer generated by default as identity, results_count integer, user_id integer, created_at timestamp(6) not null, search_type varchar(50), query varchar(255) not null, primary key (id));
create table voice_commands (id integer generated by default as identity, user_id integer not null, created_at timestamp(6) not null, status varchar(20) not null, detected_intent varchar(50), action_taken TEXT, response_text TEXT, result_data TEXT, transcribed_text TEXT not null, primary key (id));

create table password_reset_codes (used boolean not null, created_at timestamp(6) with time zone not null, expires_at timestamp(6) with time zone not null, id bigint generated by default as identity, email varchar(150) not null, code_hash varchar(255) not null, primary key (id));

create index idx_audit_user_id on audit_logs (user_id);
create index idx_audit_entity on audit_logs (entity_type, entity_id);
create index idx_audit_action on audit_logs (action);
create index idx_audit_created_at on audit_logs (created_at);
create index idx_bookview_user_id on book_views (user_id);
create index idx_bookview_book_id on book_views (book_id);
create index idx_bookmarks_user on bookmarks (user_id);
create index idx_book_title on books (title);
create index idx_book_isbn on books (isbn);
create index idx_book_isbn13 on books (isbn13);
create index idx_book_category on books (category_id);
create index idx_borrow_user_id on borrow_records (user_id);
create index idx_borrow_book_id on borrow_records (book_id);
create index idx_borrow_status on borrow_records (status);
create index idx_borrow_due_date on borrow_records (due_date);
create index idx_finepayment_fine_id on fine_payments (fine_id);
create index idx_finepayment_user_id on fine_payments (user_id);
create index idx_fine_user_id on fines (user_id);
create index idx_fine_status on fines (status);
create index idx_notification_user_id on notifications (user_id);
create index idx_notification_user_read on notifications (user_id, is_read);
create index idx_pickup_user_id on pickup_slots (user_id);
create index idx_pickup_status on pickup_slots (status);
create index idx_reservation_user_id on reservations (user_id);
create index idx_reservation_book_id on reservations (book_id);
create index idx_reservation_status on reservations (status);
create index idx_search_user_id on search_logs (user_id);
create index idx_search_created_at on search_logs (created_at);
create index idx_voicecommand_user_id on voice_commands (user_id);

alter table if exists audio_book_tracks add constraint FKo2p98j7dli0e1sbf19oahghuk foreign key (book_id) references books;
alter table if exists book_authors add constraint FKo86065vktj3hy1m7syr9cn7va foreign key (author_id) references authors;
alter table if exists book_authors add constraint FKbhqtkv2cndf10uhtknaqbyo0a foreign key (book_id) references books;
alter table if exists book_copies add constraint FKhlawea8y2e2dv0ta58vc6f5nr foreign key (book_id) references books;
alter table if exists book_views add constraint FK52x4yrabbeqh065tdy8ykpfet foreign key (book_id) references books;
alter table if exists book_views add constraint FKnpjmbi425kyic6r6acy2fqhcn foreign key (user_id) references users;
alter table if exists books add constraint FKt7qnqdbfxmwgexf9p5t03swby foreign key (institution_id) references institutions;
alter table if exists borrow_records add constraint FK9ep13xg9kn8vo3w0ntvd08tco foreign key (book_id) references books;
alter table if exists borrow_records add constraint FKlhlt2nsgeetc0kyl355bieb10 foreign key (copy_id) references book_copies;
alter table if exists borrow_records add constraint FKnwb3dwf7gd7xml7tvfkljfcr3 foreign key (reservation_id) references reservations;
alter table if exists borrow_records add constraint FKe5k0iaamaypstfhuluoa40yom foreign key (user_id) references users;
alter table if exists categories add constraint FKsaok720gsu4u2wrgbk10b5n8d foreign key (parent_id) references categories;
alter table if exists course_books add constraint FK6pmayo5d2qk1igebof9ugut9b foreign key (book_id) references books;
alter table if exists course_books add constraint FK1n1704kdji3yofs3t311d51pc foreign key (course_id) references courses;
alter table if exists courses add constraint FK9j9pt3rv7axxvf4l2svqpwus3 foreign key (institution_id) references institutions;
alter table if exists reservations add constraint FKrsdd3ib3landfpmgoolccjakt foreign key (book_id) references books;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users add constraint FK2qqjpih9isqcs22710v8lef9w foreign key (institution_id) references institutions;
