-- Email verification for student self-registration (POST /api/auth/register). Default
-- TRUE so every existing account, and every OTHER signup path (librarian, school admin,
-- platform admin, admin-created via POST /api/users), is completely unaffected - only the
-- new student self-registration path explicitly sets this FALSE on creation, and
-- AuthService.login() rejects an unverified account.
--
-- Rollback: see rollback/R7__drop_email_verification.sql

ALTER TABLE users ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT TRUE;

-- Mirrors password_reset_codes' shape/types exactly (see PasswordResetCode.java) - same
-- one-time, hashed, expiring, single-use code pattern, just for a different purpose.
CREATE TABLE email_verification_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_email_verification_codes_email ON email_verification_codes(email);
