spring.application.name=LibraLink
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Give the application extra time to establish and validate heavy metadata requests
spring.datasource.hikari.connection-timeout=45000
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.keepalive-time=30000

# Fixes issues with metadata reads during initialization
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
