-- Manual rollback for V5__enforce_not_null.sql. Not auto-run by Flyway.
ALTER TABLE books ALTER COLUMN institution_id DROP NOT NULL;

ALTER TABLE borrow_records           ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE fines                    ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE fine_payments            ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE reservations             ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE pickup_slots             ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE notifications            ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE reading_lists            ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE reading_list_items       ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE student_reading_progress ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE book_copies              ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE book_views               ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE audio_tracks             ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE audio_book_tracks        ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE exam_questions           ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE study_sessions           ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE study_summaries          ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE user_audio_progress      ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE audit_logs               ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE search_logs              ALTER COLUMN school_id DROP NOT NULL;
ALTER TABLE voice_commands           ALTER COLUMN school_id DROP NOT NULL;
